#Problem
#In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
#The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

#Given: A DNA string s of length at most 1000 bp.
#Return: The reverse complement sc of s.

dna = 'ATCTGCACAATGAACGATTAAGGACGATGGAGTCGGCAATCTACAGGCGCCGGTAGTACGGCCCCATACGCCTGTGCCGTCACTGCGATAACTTCGCCATTTAATCACTTTAGACGCCGTATAATGAATAGGGGTTGCGTGGAAACCGGCCGGGTCGAATATGAAGTGAAGACGTCTGGTTGTACTAATTCAAATTGGTGAGTCTCTTACAGGTTTTAAAAGGAGCACTCAGTGCTTATAGGAAGGTCTGAGCGTCAGTGGCCTAAGTCGTGGTTATCAAGAGATACGCCGAGCTGCTGTACCGTTATACCCATCTCTCGATACGAGGCACTTACATGTAGCCCATAGGAGACAGACTCCCGAAAACTAGGGGTGATGGTTATGAAAGACCCAATCGGTTTAGAGGTTGTCCGTGTGGCAACCGATATGGCAGAGAGCGCTGGGTTAGATGGACGACCATAAGTGGGGGGGAGGCCGTTACTGAACATACCCGATACACGCGCTGTTTCTTCTCTGAGTCAACGAGGCTGGCCCACGTCGTACCAGAGCTCTAATTAGCCCTTGAGCCCCGTGCCTCAGCAGGATGGTGCATAGAATTCTAACCCTGCCCGCTTCTGGACGAGCCGCAATAACTGATGATTTGAGAGTTATAACCCATCTAGCGCAGGTCGCGGGTGCCCAACTTACAAACTGCCAAAGGTGAAGCCATGGCGCTAGCCCTATTCTACATCAGTCCTTGTTAGCGTCCTAATCCTACCAACCACAAGGTGTAGAACGCGACATTAATTAAATAGATGTTGTTCATATCGAAGACCTCGTACGAAACCTGAACGTTTATTCTTTCGGCCTGAACCTCCCTCGTAACAGGCATAAGTAAAGCAAAACTGCAGAATCGTCTCCTCCAGTTTTCGGGCACGCCGCCGCCTAAGAACTTCATAGGCTTGGGTGCCGTTTTCCTTTACTCGCTAATCCTCTTCAAGAGTTCGTTGTCGGGCACC'
rev_dna = ''

for i in range(0, len(dna)):
    if dna[i] == 'T':
        rev_dna += 'A'
    elif dna[i] == 'A':
        rev_dna += 'T'
    elif dna[i] == 'G':
        rev_dna += 'C'
    elif dna[i] == 'C':
        rev_dna += 'G'

def my_function(x):
    return x[::-1]

rev_dna = my_function(rev_dna)

print(rev_dna)